FIELD_MAPS_TO_CHOICES = (
    ('first_name', 'First name'),
    ('middle_name', 'Middle name'),
    ('last_name', 'Last name'),
    ('previous_name', 'Previous name'),
    ('phone_number', 'Phone number'),
    ('mobile_number', 'Mobile number'),
    ('email', 'Email'),
    ('birth_date', 'Birth date'),
    ('identification', 'Identification'),
    ('marital_status', 'Marital status'),
    ('co_applicant_first_name', 'Co-applicant first name'),
    ('co_applicant_middle_name', 'Co-applicant middle name'),
    ('co_applicant_last_name', 'Co-applicant last name'),
    ('co_applicant_previous_name', 'Co-applicant previous name'),
    ('co_applicant_phone_number', 'Co-applicant phone number'),
    ('co_applicant_mobile_number', 'Co-applicant mobile number'),
    ('co_applicant_email', 'Co-applicant email'),
    ('co_applicant_birth_date', 'Co-applicant birth date'),
    ('co_applicant_identification', 'Co-applicant identification'),
    ('co_applicant_marital_status', 'Co-applicant marital status'),
    ('dependants', 'Dependants'),
    ('address_1', 'Address line 1'),
    ('address_2', 'Address line 2'),
    ('city', 'City'),
    ('state', 'State'),
    ('zip_code', 'Zip code'),
    ('residential_status', 'Residential status'),
    ('co_applicant_address_1', 'Co-applicant address line 1'),
    ('co_applicant_address_2', 'Co-applicant address line 2'),
    ('co_applicant_city', 'Co-applicant city'),
    ('co_applicant_state', 'Co-applicant state'),
    ('co_applicant_zip_code', 'Co-applicant zip code'),
    ('employer', 'Employer'),
    ('employment_status', 'Employment status'),
    ('position', 'Position'),
    ('length_of_employment', 'Length of employment'),
    ('work_phone', 'Work phone'),
    ('co_applicant_employer', 'Co-applicant employer'),
    ('co_applicant_employment_status', 'Co-applicant employment status'),
    ('co_applicant_position', 'Co-applicant position'),
    ('co_applicant_length_of_employment', 'Co-applicant length of employment'),
    ('co_applicant_work_phone', 'Co-applicant work phone'),
    ('hardships', 'Hardships'),
    ('hardship_description', 'Hardship description'),
    ('special_note_1', 'Special note 1'),
    ('special_note_2', 'Special note 2'),
    ('special_note_3', 'Special note 3'),
    ('special_note_4', 'Special note 4'),
    ('ssn1', 'SSN'),
    ('ssn2', 'Co-applicant SSN'),
    ('third_party_speaker_full_name', 'Third party speaker full name'),
    ('third_party_speaker_last_4_of_ssn', 'Third party speaker last 4 of SSN'),
    ('authorization_form_on_file', 'Authorization form on file'),
)


# Original fields:

#   ('Standard fields', (
#       ('num_summons', '# Summons'),
#       ('first_payment_amount', '1st Payment Amount'),
#       ('first_payment_date', '1st Payment Date'),
#       ('second_payment_amount', '2nd Payment Amount'),
#       ('second_payment_date', '2nd Payment Date'),
#       ('third_payment_amount', '3rd Payment Amount'),
#       ('third_payment_date', '3rd Payment Date'),
#       ('address', 'Address 1'),
#       ('address2', 'Address 2'),
#       ('approved_by', 'Approved By'),
#       ('approved_date', 'Approved Date'),
#       ('attorney_id', 'Assigned Attorney'),
#       ('assigned_lawfirm', 'Assigned Law Firm'),
#       ('assigned_leadvendor', 'Assigned Lead Vendor'),
#       ('assigned_marketing', 'Assigned Marketing'),
#       ('assigned_on', 'Assigned On'),
#       ('assigned_partner', 'Assigned Partner'),
#       ('assigned_servicing', 'Assigned Servicing'),
#       ('assigned_to', 'Assigned To'),
#       ('balance', 'Balance'),
#       ('company', 'Business Name'),
#       ('campaign_id', 'Campaign'),
#       ('phone3', 'Cell Phone'),
#       ('city', 'City'),
#       ('coapp', 'Co-Applicant'),
#       ('coappssn', 'Co-Applicant SSN'),
#       ('comments', 'Comments'),
#       ('company_id', 'Company'),
#       ('created', 'Created'),
#       ('created_by', 'Created By'),
#       ('c_source', 'Data Source'),
#       ('dob', 'Date Of Birth'),
#       ('days_enrolled', 'Days Enrolled'),
#       ('department', 'Department'),
#       ('dropped', 'Dropped'),
#       ('dropped_date', 'Dropped Date'),
#       ('email', 'Email'),
#       ('email2', 'Email 2'),
#       ('enrolled', 'Enrolled'),
#       ('enrolled_date', 'Enrolled Date'),
#       ('enrolled_debt', 'Enrolled Debt'),
#       ('equitable_status', 'Equitable Status'),
#       ('equitable_status_date', 'Equitable Status Date'),
#       ('tp_id', 'External ID'),
#       ('fax', 'Fax'),
#       ('file_type', 'File Type'),
#       ('first_name', 'First Name'),
#       ('siteID', 'From Site'),
#       ('fullname', 'Full Name'),
#       ('full_status', 'Full Status'),
#       ('gateway_id', 'Gateway'),
#       ('graduated', 'Graduated'),
#       ('grad_date', 'Graduation Date'),
#       ('phone', 'Home Phone'),
#       ('inactive_days', 'Inactive Days'),
#       ('language', 'Language'),
#       ('last_advance_amount', 'Last Advance Amount'),
#       ('last_advance_date', 'Last Advance Date'),
#       ('last_advance_status', 'Last Advance Status'),
#       ('last_event', 'Last Cal Event'),
#       ('last_activity', 'Last Call Activity'),
#       ('last_call_disp', 'Last Call Disp'),
#       ('last_connected', 'Last Connected'),
#       ('last_esign', 'Last E-Sign Status'),
#       ('last_history_date', 'Last History Date'),
#       ('last_history_type', 'Last History Type'),
#       ('last_history_user', 'Last History User'),
#       ('lastname', 'Last Name'),
#       ('last_note', 'Last Note'),
#       ('last_note_by', 'Last Note By'),
#       ('last_note_date', 'Last Note Date'),
#       ('last_note_type', 'Last Note Type'),
#       ('last_payment_amount', 'Last Payment Amount'),
#       ('last_payment_cleared_date', 'Last Payment Cleared Date'),
#       ('last_payment_date', 'Last Payment Date'),
#       ('last_payment_status', 'Last Payment Status'),
#       ('last_status_date', 'Last Status Date'),
#       ('middlename', 'Middle Name'),
#       ('modified', 'Modified'),
#       ('modified_by', 'Modified By'),
#       ('months_enrolled', 'Months Enrolled'),
#       ('next_event', 'Next Cal Event'),
#       ('next_payment', 'Next Payment'),
#       ('next_payment_amount', 'Next Payment Amount'),
#       ('next_payment_type', 'Next Payment Type'),
#       ('opened_campaign', 'Opened Campaign'),
#       ('unsubscribe', 'Opt-Out'),
#       ('phone4', 'Other Phone'),
#       ('parent_id', 'Parent Contact'),
#       ('paused', 'Paused'),
#       ('payment_completion_p', 'Payment Completion %'),
#       ('payments_made', 'Payments Made'),
#       ('pending', 'Pending Balance'),
#       ('extension2', 'Phone 2 Ext'),
#       ('phone2type', 'Phone 2 Type'),
#       ('extension', 'Phone Ext'),
#       ('phonetype', 'Phone Type'),
#       ('program_name', 'Program Name'),
#       ('program_start_date', 'Program Start Date'),
#       ('stuloan_program', 'Repayment Program'),
#       ('reports_to', 'Reports To'),
#       ('returned_at', 'Returned Date'),
#       ('ssn', 'SSN'),
#       ('approved_date2', 'Secondary Approval Date'),
#       ('settled_per', 'Settled %'),
#       ('settlement_commitment', 'Settlement Commitment'),
#       ('c_type', 'Stage'),
#       ('state', 'State'),
#       ('leadstatus', 'Status'),
#       ('stuloan_term', 'Student Loan Months'),
#       ('stuloan_payment', 'Student Loan Payment'),
#       ('submitted_by', 'Submitted By'),
#       ('submitted_at', 'Submitted Date'),
#       ('time_in_status', 'Time In Status'),
#       ('title', 'Title'),
#       ('total_debt', 'Total Debt'),
#       ('url', 'URL'),
#       ('unsettled_debt', 'Unsettled Debt'),
#       ('unsubscribe', 'Unsubscribe'),
#       ('phone2', 'Work Phone'),
#       ('zip', 'Zip'),
#   )),

#   ('Custom Fields', (
#       ('125206', 'CFLN Settlement 6 Creditor & Last 4 of Acct#:'),
#       ('37456', '*Eppsbal'),
#       ('37465', '*Eppsbal Last Updated'),
#       ('74709', '*First Payment Cleared'),
#       ('44890', '*Last Payment Cleared'),
#       ('24963', '*Lead Source* '),
#       ('30651', '*Trust Account Provider'),
#       ('12242', '3rd Party Speaker Full Name'),
#       ('12243', '3rd Party Speaker Last 4 of SSN'),
#       ('22596', 'Adjusted Gross Income'),
#       ('22599', 'Adjusted Gross Income (Spouse)'),
#       ('22617', 'Alias'),
#       ('6810', 'Appointment Date'),
#       ('6812', 'Appointment Time'),
#       ('6932', 'ATC'),
#       ('44923', 'ATC Sent To All Creditors'),
#       ('12255', 'Authorization Form On File'),
#       ('4889', 'Best Time to Contact (PST - 2 hour block)'),
#       ('128009', 'call'),
#       ('130734', 'Call'),
#       ('68857', 'Call Center Representative'),
#       ('13782', 'Cancellation Letter Sent'),
#       ('12246', 'CC Debt Amount'),
#       ('86709', 'CFLN Settlement 1 Creditor & Last 4 of Acct#:'),
#       ('86685', 'CFLN Settlement 1 Date'),
#       ('86712', 'CFLN Settlement 2 Creditor & Last 4 of Acct#:'),
#       ('86688', 'CFLN Settlement 2 Date'),
#       ('86715', 'CFLN Settlement 3 Creditor & Last 4 of Acct#:'),
#       ('86694', 'CFLN Settlement 3 Date'),
#       ('86718', 'CFLN Settlement 4 Creditor & Last 4 of Acct#:'),
#       ('86700', 'CFLN Settlement 4 Date'),
#       ('86748', 'CFLN Settlement 5 Creditor & Last 4 of Acct#:'),
#       ('86706', 'CFLN Settlement 5 Date'),
#       ('125197', 'CFLN Settlement 6 Date'),
#       ('125209', 'CFLN Settlement 7 Creditor & Last 4 of Acct#:'),
#       ('125203', 'CFLN Settlement 7 Date'),
#       ('6836', 'Change Contact Info Requested'),
#       ('86679', 'Client had delinquent accounts in program when enrolled?'),
#       ('4885', 'Co-Applicant'),
#       ('22620', 'Consolidations'),
#       ('22719', 'Consolidations Prior'),
#       ('6738', 'Contact Info Updated'),
#       ('79597', 'Creditor Account Num'),
#       ('79589', 'Creditor Name'),
#       ('22623', 'Current Status of Loans'),
#       ('17798', 'De-Enrolled Date'),
#       ('54211', 'Dependents (total for both applicants)'),
#       ('22626', 'DL Number'),
#       ('22629', 'DL State'),
#       ('4886', 'Employer'),
#       ('22632', 'Employer Address'),
#       ('22635', 'Employer Address2'),
#       ('22638', 'Employer City'),
#       ('22641', 'Employer State'),
#       ('22644', 'Employer Zip'),
#       ('53419', 'Employment Status'),
#       ('22602', 'Family Size'),
#       ('22647', 'File Taxes'),
#       ('22593', 'Filing Status'),
#       ('46807', 'Fremont Group POA On File?'),
#       ('5289', 'Goal Once Debt Free'),
#       ('13785', 'Graduation Letter Sent'),
#       ('4891', 'Hardship Description'),
#       ('37084', 'Hardship Notification Letters Sent'),
#       ('4892', 'Hardships'),
#       ('6931', 'HNL'),
#       ('6929', 'HS'),
#       ('6930', 'I&E'),
#       ('22728', 'Income Year'),
#       ('6604', 'Kill Date'),
#       ('6603', 'Kill Reason'),
#       ('8300', 'Last Congratulatons Letter Sent'),
#       ('20602', 'Last MAR Completed'),
#       ('8532', 'Last NSF Letter Sent'),
#       ('30642', 'Last NSF Letter Sent Type'),
#       ('8534', 'Last Paused Letter Sent'),
#       ('35469', 'Last Retention Letter Sent'),
#       ('8533', 'Last Settlement Authorization Needed Letter Sent'),
#       ('30648', 'Last Settlement Authorization Needed Letter Sent Type'),
#       ('8181', 'Last Settlement Completed'),
#       ('18420', 'Last Settlement Review'),
#       ('40405', 'Last UC Correspondence Sent To Client'),
#       ('12177', 'Lead Debt Amount'),
#       ('22722', 'Lead Source'),
#       ('22734', 'Lead Type'),
#       ('22614', 'Length of Employment'),
#       ('22731', 'Loan Type'),
#       ('22650', 'Maiden Name'),
#       ('6566', 'MAR Due'),
#       ('6816', 'MAR Time'),
#       ('12224', 'MAR Type'),
#       ('53413', 'Marital Status'),
#       ('35676', 'Notarized ATC On File?'),
#       ('18422', 'Number of Accounts Reviewed'),
#       ('22737', 'Other Debt'),
#       ('22653', 'Pay Frequency'),
#       ('22590', 'PIN Number'),
#       ('22656', 'PIN Requested'),
#       ('4888', 'Position'),
#       ('6826', 'Previous Name'),
#       ('22659', 'REF1 Address'),
#       ('22662', 'REF1 City'),
#       ('22665', 'REF1 Name'),
#       ('22668', 'REF1 Phone'),
#       ('22671', 'REF1 Relationship'),
#       ('22674', 'REF1 State'),
#       ('22677', 'REF1 Zip'),
#       ('22680', 'REF2 Address'),
#       ('22683', 'REF2 City'),
#       ('22686', 'REF2 Name'),
#       ('22689', 'REF2 Phone'),
#       ('22692', 'REF2 Relationship'),
#       ('22695', 'REF2 State'),
#       ('22698', 'REF2 Zip'),
#       ('22725', 'Referred By'),
#       ('130737', 'Represen'),
#       ('53416', 'Residential Status'),
#       ('9811', 'S1 Date'),
#       ('5277', 'Salesman Email Address'),
#       ('5276', 'Salesman Name'),
#       ('5278', 'Salesman Phone Number'),
#       ('141289', 'Sett 1 Date Completed'),
#       ('141616', 'Sett 1 Original Creditor and Last 4'),
#       ('141286', 'Sett 1 Revenue Earned This Month'),
#       ('141622', 'Sett 2 Date Completed'),
#       ('141625', 'Sett 2 Original Creditor and Last 4'),
#       ('141619', 'Sett 2 Revenue Earned This Month'),
#       ('141631', 'Sett 3 Date Completed'),
#       ('141634', 'Sett 3 Original Creditor and Last 4'),
#       ('141628', 'Sett 3 Revenue Earned This Month'),
#       ('141640', 'Sett 4 Date Completed'),
#       ('141643', 'Sett 4 Original Creditor and Last 4'),
#       ('141637', 'Sett 4 Revenue Earned This Month'),
#       ('141649', 'Sett 5 Date Completed'),
#       ('141652', 'Sett 5 Original Creditor and Last 4'),
#       ('141646', 'Sett 5 Revenue Earned This Month'),
#       ('5281', 'Special Note 1'),
#       ('5282', 'Special Note 2'),
#       ('13770', 'Special Note 3'),
#       ('13773', 'Special Note 4'),
#       ('22605', 'Spouse Indebtedness Amount'),
#       ('22713', 'Spouse Pay Frequency'),
#       ('5279', 'SSN1'),
#       ('5280', 'SSN2'),
#       ('22740', 'Student Debt'),
#       ('20596', 'STUDENT LOANS CONSOLIDATED?'),
#       ('20595', 'STUDENT LOANS?'),
#       ('22707', 'Suffix'),
#       ('20592', 'TAX ISSUES?'),
#       ('22701', 'Taxable Income'),
#       ('10160', 'Total Debt Amount'),
#       ('12223', 'Transferred?'),
#       ('52006', 'Unit(s)'),
#       ('35679', 'Unknown Creditor 1'),
#       ('35682', 'Unknown Creditor 2'),
#       ('35685', 'Unknown Creditor 3'),
#       ('35688', 'Unknown Creditor 4'),
#       ('35691', 'Unknown Creditor 5'),
#       ('22704', 'Using AGI Form'),
#       ('22716', 'Wages Garnished'),
#       ('6597', 'WC Completed'),
#       ('6596', 'WC Due'),
#       ('6817', 'WC Time'),
#       ('22710', 'Welcome Call Date'),
#       ('143809', 'Welcome Call Was A Live Transfer?'),
#   )),

#   ('Other', (
#       ('__object_note', '---Create New Note---'),
#   )),
